2025-09-11 12:49:18 UTC
Linux-6.16.6-2-cachyos-x86_64-with-glibc2.42
Ren'Py 8.4.2.25091001+nightly

Early init took 19 ms
Loading error handling took 13 ms
Loading script took 274 ms
Loading save slot metadata took 1 ms
Loading persistent took 0 ms
Running init code took 21 ms
Loading analysis data took 0 ms
Analyze and compile ATL took 1 ms
Reloading save slot metadata took 0 ms
Dump and make backups took 0 ms
Cleaning cache took 0 ms
Making clean stores took 0 ms
Initial gc took 16 ms
DPI scale factor: 1.000000
Creating interface object took 0 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 0 ms
Analyze screens took 8 ms
Save screen analysis took 4 ms
Save pyanalysis took 1 ms
Save bytecode took 10 ms
Running _start took 1 ms
Interface start took 158 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'NVIDIA Corporation'
Renderer: 'NVIDIA GeForce RTX 4080 SUPER/PCIe/SSE2'
Version: '4.6.0 NVIDIA 580.82.07'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1080, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(800, 600) physical=(800, 600) drawable=(800, 600)
Maximum texture size: 4096x4096
Could not open 'cache/shaders.txt':
controller: '030000004c050000e60c000000016800' 'PS5 Controller' 1

Full traceback:
  File "renpy/common/00start.rpy", line 291, in script
    python:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 1273, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 293, in <module>
    renpy.jump("start")
  File "renpy/exports/statementexports.py", line 271, in jump
    raise renpy.game.JumpException(label)
renpy.game.JumpException: start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "renpy/bootstrap.py", line 376, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 614, in main
    run(restart)
  File "renpy/main.py", line 137, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 1022, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 291, in script
    python:
  File "renpy/script.py", line 1161, in lookup
    raise LabelNotFound(original)
renpy.script.LabelNotFound: could not find label 'start'.

While running game code:
renpy.game.JumpException: start

During handling of the above exception, another exception occurred:

renpy.script.LabelNotFound: could not find label 'start'.
